export const adminRoutes = [
  {
    href: "/admin/dashboard",
    src: "/admin/sidebar/dashboardDark.svg",
    activeSrc: "/admin/sidebar/dashboard.svg",
    title: "DASHBOARD",
  },
  {
    href: "/admin/enigma",
    src: "/admin/sidebar/enigmaDark.svg",
    activeSrc: "/admin/sidebar/enigma.svg",
    title: "ENIGMA",
  },
  {
    href: "/admin/clash",
    src: "/admin/sidebar/clashDark.svg",
    activeSrc: "/admin/sidebar/clash.svg",
    title: "CLASH",
  },
  {
    href: "/admin/riddles",
    src: "/admin/sidebar/riddlesDark.svg",
    activeSrc: "/admin/sidebar/riddles.svg",
    title: "RIDDLES",
  },
  {
    href: "/admin/finance",
    src: "/admin/sidebar/financeDark.svg",
    activeSrc: "/admin/sidebar/finance.svg",
    title: "FINANCE",
  },
  {
    href: "/admin/faq",
    src: "/admin/sidebar/faqDark.svg",
    activeSrc: "/admin/sidebar/faq.svg",
    title: "FAQS",
  },
  {
    href: "/admin/users",
    src: "/admin/sidebar/userDark.svg",
    activeSrc: "/admin/sidebar/user.svg",
    title: "USERS",
  },
];

export const dashboardCardsData = [
  { title: "Total Profit", percentage: "+8.6%", value: "721,000" },
  { title: "Hints", percentage: "+8.6%", value: "721,000" },
  { title: "Lives", percentage: "+8.6%", value: "721,000" },
  { title: "Tournaments", percentage: "+8.6%", value: "721,000" },
];

export const profitChartLabels: string[] = [
  "Jan 1–15",
  "Jan 16–31",
  "Feb 1–15",
  "Feb 16–28",
  "Mar 1–15",
  "Mar 16–31",
  "Apr 1–15",
  "Apr 16–30",
  "May 1–15",
  "May 16–31",
  "Jun 1–15",
  "Jun 16–30",
  "Jul 1–15",
  "Jul 16–31",
  "Aug 1–15",
  "Aug 16–31",
  "Sep 1–15",
  "Sep 16–30",
  "Oct 1–15",
  "Oct 16–31",
  "Nov 1–15",
  "Nov 16–30",
  "Dec 1–15",
  "Dec 16–31",
];

export const transactions = [
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
];

export const seasons = [
  { number: 5, status: "Active", title: "Riddle Title" },
  { number: 5, status: "Inactive", title: "Another Title" },
  { number: 5, status: "Active", title: "Third Title" },
  { number: 5, status: "Inactive", title: "Speed Quiz" },
  { number: 5, status: "Active", title: "Brain Busters" },
  { number: 5, status: "Active", title: "Fast Fingers" },
  { number: 5, status: "Inactive", title: "Trivia Titans" },
  { number: 5, status: "Inactive", title: "Quick Solve" },
  { number: 5, status: "Active", title: "Mind Marathon" },
  { number: 5, status: "Inactive", title: "Puzzle Race" },
  { number: 5, status: "Inactive", title: "Logic Wars" },
  { number: 5, status: "Active", title: "Memory Match" },
];

export const tournaments = [
  { id: "#CM9801", title: "Riddle Title", paid: "€10", status: "Active" },
  { id: "#CM9802", title: "Another Title", paid: "Paid", status: "Concluded" },
  { id: "#CM9803", title: "Third Title", paid: "Paid", status: "Pending" },
  { id: "#CM9804", title: "Speed Quiz", paid: "€15", status: "Active" },
  { id: "#CM9805", title: "Brain Busters", paid: "Paid", status: "Concluded" },
  { id: "#CM9806", title: "Fast Fingers", paid: "€8", status: "Pending" },
  { id: "#CM9807", title: "Trivia Titans", paid: "Paid", status: "Concluded" },
  { id: "#CM9808", title: "Quick Solve", paid: "€12", status: "Active" },
  { id: "#CM9809", title: "Mind Marathon", paid: "€5", status: "Pending" },
  { id: "#CM9810", title: "Puzzle Race", paid: "Paid", status: "Concluded" },
  { id: "#CM9811", title: "Logic Wars", paid: "€20", status: "Active" },
  { id: "#CM9812", title: "Memory Match", paid: "Paid", status: "Pending" },
];

export const riddles = [
  {
    levelId: "#CM9811",
    title: "Logic Puzzle",
    solution: "Tree",
    hint1: "It grows",
    hint2: "Has leaves",
    hint3: "Found in forests",
  },
  {
    levelId: "#CM9812",
    title: "Math Challenge",
    solution: "42",
    hint1: "A number",
    hint2: "6 x 7",
    hint3: "Answer to everything",
  },
  {
    levelId: "#CM9814",
    title: "Shape Quiz",
    solution: "Circle",
    hint1: "No corners",
    hint2: "Perfectly round",
    hint3: "A pizza has it",
  },
  {
    levelId: "#CM9815",
    title: "Animal Mystery",
    solution: "Cat",
    hint1: "Meows",
    hint2: "Loves naps",
    hint3: "Hates water",
  },
  {
    levelId: "#CM9816",
    title: "Science Fact",
    solution: "Gravity",
    hint1: "Keeps us grounded",
    hint2: "Invisible force",
    hint3: "Discovered by Newton",
  },
  {
    levelId: "#CM9817",
    title: "History Check",
    solution: "Napoleon",
    hint1: "Short man",
    hint2: "French leader",
    hint3: "Waterloo",
  },
  {
    levelId: "#CM9818",
    title: "Space Riddle",
    solution: "Moon",
    hint1: "Shines at night",
    hint2: "Has craters",
    hint3: "Affects tides",
  },
  {
    levelId: "#CM9819",
    title: "Color Logic",
    solution: "Orange",
    hint1: "Fruit and color",
    hint2: "Between red and yellow",
    hint3: "No rhymes",
  },
  {
    levelId: "#CM9820",
    title: "Tech Trivia",
    solution: "JavaScript",
    hint1: "Web language",
    hint2: "Not Java",
    hint3: "Runs in browsers",
  },
];

export const finance = [
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9801",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9802",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "HINT",
  },
  {
    orderId: "#CM9803",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
  {
    orderId: "#CM9804",
    accountId: "Natali Craig",
    value: "€4.99",
    date: "26/04/2025 17:55",
    status: "LIVE",
  },
];
