import BaseLayout from "@/components/layouts/BaseLayout";
import "../styles/globals.css";
import "../styles/globals.scss";
import Script from "next/script";
import ToastProvider from "@/components/common/toaster/Toastify";

export const metadata = {
  title: "Rev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Script
          src="https://js.stripe.com/v3/"
          strategy="beforeInteractive"
        />
        <ToastProvider />
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
